# Synology group specific variables

# User / Group
servarr_uid: "1027"
servarr_gid: "65538"

# Timezone
timezone: "Europe/London"

# Filepaths
config_directory: "/volume2/homes/servarr/config"
data_directory: "/volume3/servarr"

# File permissions
directory_mode: "775"
file_mode: "664"

# Docker
docker_state: "started"
docker_restart: "no"
docker_restart_policy: "unless-stopped"
docker_recreate: "no"

# DNS
dns_primary: "1.1.1.1"
dns_secondary: "1.0.0.1"

# Network
network_subnet: "{{ vault_network_subnet }}"
network_gateway: "{{ vault_network_gateway }}"
network_tailscale_ip: "{{ vault_network_tailscale_ip }}"
network_tailnet: "{{ vault_network_tailnet }}"
network_tailscale_machine: "{{ vault_network_tailscale_machine }}"
