# Synology group specific variables

# User / Group
servarr_uid: "1027"
servarr_gid: "65538"

# Filepaths
config_directory: "/volume3/homes/servarr/config"
data_directory: "/volume3/servarr"

# Docker
docker_network: "docker_network_synology"
docker_socket_proxy_port: "2375"

# Network
network_localhost: "192.168.1.164"

# Tailscale
tailnet_synology_machine: "{{ vault_tailnet_synology_machine }}"