---
- name: Start container
  tags:
    - overseerr
    - container
  docker_container:
    name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    state: "{{ docker_state }}"
    restart: "{{ docker_restart }}"
    restart_policy: "{{ docker_restart_policy }}"
    recreate: "{{ docker_recreate }}"
    volumes:
      - "{{ config_directory }}/overseerr:/config"
      - "{{ data_directory }}:/data"
    ports:
      - "{{ host_port }}:5055"
    dns_servers:
      - "{{ dns_primary }}"
      - "{{ dns_secondary }}"
    env:
      PUID: "{{ servarr_uid }}"
      PGID: "{{ servarr_gid }}"
      TZ: "{{ timezone }}"
    labels:
      traefik.enable: "false"
      homepage.group: "Media"
      homepage.name: "Overseerr"
      homepage.icon: "overseerr.png"
      homepage.description: "Request stuff"
      homepage.href: "http://{{ network_localhost }}:{{ host_port }}"
      homepage.widget.type: overseerr
      homepage.widget.url: "http://{{ network_localhost }}:{{ host_port }}"
      homepage.widget.key: "{{ overseerr_api_key }}"
