---
- name: Start container
  tags: 
    - overseerr
    - container
  docker_container:
    name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    state: started
    restart_policy: always
    restart: '{{ docker_restart }}'
    recreate: '{{ docker_recreate }}'
    volumes:
      - '{{ config_directory }}/overseerr:/config'
      - '{{ data_directory }}:/data'
    ports:
      - '{{ host_port }}:5055'
    dns_servers:
      - '{{ dns_primary }}'
      - '{{ dns_secondary }}'
    env:
      PUID: '{{ servarr_uid }}'
      PGID: '{{ servarr_gid }}'
      TZ: '{{ timezone }}'