---
- name: Ensure config directory is present
  tags:
    - overseerr
    - config
  file:    
    path: '{{ config_directory }}/overseerr'
    state: directory
    owner: servarr
    group: servarr
    mode: '{{ directory_mode }}'