- name: Synology Media Server
  hosts: synology
  become: true
  vars_files:
    - vars/main.yml
    - vars/vault.yml
  roles:
    - homepage
    - cloudflared
    - transmission
    - transmission-openvpn
    - plex
    - sonarr
    - radarr
    - prowlarr
    - bazarr
    - overseerr
    - flaresolverr
    - watchtower
