---
- name: Ensure config directory is present with correct permissions
  file:
    path: "{{ config_directory }}/watchtower"
    state: directory
    owner: servarr
    group: servarr
    mode: "{{ directory_mode }}"

- name: Template config file
  template:
    src: "config.json.j2"
    dest: "{{ watchtower_config_filepath }}"
    owner: servarr
    group: servarr
    mode: "{{ file_mode }}"