---
docker_image_version: "v3.1"
traefik_config_directory: "{{ config_directory }}/traefik"

# Reuse the existing macvlan network created by adguard-home
# (only one macvlan network per subnet is allowed)
traefik_macvlan_network: "adguard_network"
traefik_ip: "192.168.1.167"

# Local domain for routing rules
traefik_home_domain: "home.arpa"

# Log configuration
log_level: "INFO"
