---
host_port: "443"
docker_image_version: "v3.1"
traefik_config_directory: "{{ config_directory }}/traefik"

# Network configuration
traefik_web_port: "80"
traefik_websecure_port: "443"

# Tailscale domain
traefik_domain: "{{ tailnet_synology_machine }}.{{ tailnet_host }}"

# Log configuration
log_level: "INFO"
