# Radarr container
# Docker Hub: https://hub.docker.com/r/linuxserver/radarr
# Docs: https://docs.linuxserver.io/images/docker-radarr
---
- name: Start container
  tags:
    - radarr
    - container
  docker_container:
    name: radarr
    image: linuxserver/radarr
    state: "{{ docker_state }}"
    restart: "{{ docker_restart }}"
    restart_policy: "{{ docker_restart_policy }}"
    recreate: "{{ docker_recreate }}"
    volumes:
      - "{{ config_directory }}/radarr:/config"
      - "{{ data_directory }}:/data"
    ports:
      - "{{ host_port }}:7878"
    dns_servers:
      - "{{ dns_primary }}"
      - "{{ dns_secondary }}"
    env:
      PUID: "{{ servarr_uid }}"
      PGID: "{{ servarr_gid }}"
      TZ: "{{ timezone }}"
    labels:
      traefik.enable: "false"
