# Homepage container
# https://github.com/gethomepage/homepage
---
- name: Start container
  tags:
    - homepage
    - container
  docker_container:
    name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    state: "{{ docker_state }}"
    restart: "{{ docker_restart }}"
    restart_policy: "{{ docker_restart_policy }}"
    recreate: "{{ docker_recreate }}"
    volumes:
      - "{{ config_directory }}/homepage:/app/config"
    ports:
      - "{{ host_port }}:3000"
    networks:
      - name: "{{ docker_network }}"
    dns_servers:
      - "{{ dns_primary }}"
      - "{{ dns_secondary }}"
    env:
      DOCKER_HOST: "tcp://docker-socket-proxy:{{ docker_socket_proxy_port }}"
      HOMEPAGE_ALLOWED_HOSTS: "gethomepage.dev,{{ network_localhost }}:{{ host_port }}"
      PUID: "{{ servarr_uid }}"
      PGID: "{{ servarr_gid }}"
      TZ: "{{ timezone }}"
    labels:
      traefik.enable: "false"