# Prowlarr container
# Docker Hub: https://hub.docker.com/r/linuxserver/prowlarr
# Docs: https://docs.linuxserver.io/images/docker-prowlarr
---
- name: Start container
  tags:
    - prowlarr
    - container
  docker_container:
    name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    state: "{{ docker_state }}"
    restart: "{{ docker_restart }}"
    restart_policy: "{{ docker_restart_policy }}"
    recreate: "{{ docker_recreate }}"
    volumes:
      - "{{ config_directory }}/prowlarr:/config"
    ports:
      - "{{ host_port }}:9696"
    dns_servers:
      - "{{ dns_primary }}"
      - "{{ dns_secondary }}"
    env:
      PUID: "{{ servarr_uid }}"
      PGID: "{{ servarr_gid }}"
      TZ: "{{ timezone }}"
    labels:
      traefik.enable: "false"
