# Sonarr container
# Docker Hub: https://hub.docker.com/r/linuxserver/sonarr
# Docs: https://docs.linuxserver.io/images/docker-sonarr
---
- name: Start container
  tags:
    - sonarr
    - container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    state: "{{ docker_state }}"
    restart: "{{ docker_restart }}"
    restart_policy: "{{ docker_restart_policy }}"
    recreate: "{{ docker_recreate }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ config_directory }}/sonarr:/config"
      - "{{ data_directory }}:/data"
    ports:
      - "{{ host_port }}:8989"
    dns_servers:
      - "{{ dns_primary }}"
      - "{{ dns_secondary }}"
    env:
      PUID: "{{ servarr_uid }}"
      PGID: "{{ servarr_gid }}"
      TZ: "{{ timezone }}"
    labels:
      traefik.enable: "false"
      homepage.group: "Media"
      homepage.name: "Sonarr"
      homepage.href: "{{ network_localhost }}:{{ host_port }}"
      homepage.description: "Sonarr"
