# Set up file structure
#
# home
# └── config
#     ├── transmission-films
#     ├── transmission-tv
#     └── transmission-other
# servarr
# └── torrents
#     ├── films
#     │   ├── completed
#     │   ├── incomplete
#     │   └── watch
#     ├── tv
#     │   ├── completed
#     │   ├── incomplete
#     │   └── watch
#     └── other
#         ├── completed
#         ├── incomplete
#         └── watch
---
- name: Ensure config directories are present
  tags: config
  file:    
    path: '{{ config_directory }}/{{ item }}'
    state: directory
    owner: servarr
    group: servarr
    mode: '{{ directory_mode }}'
  loop: 
    - 'transmission-films'
    - 'transmission-tv'
    - 'transmission-other'

- name: Ensure torrents directories are present
  tags: config
  file:    
    path: '{{ data_directory }}/torrents/{{ item }}'
    state: directory
    owner: servarr
    group: servarr
    mode: '{{ directory_mode }}'
  loop:
    - 'films/completed'
    - 'films/incomplete'
    - 'films/watch'
    - 'tv/completed'
    - 'tv/incomplete'
    - 'tv/watch'
    - 'other/completed'
    - 'other/incomplete'
    - 'other/watch'