---
- name: Create unrar script
  template:
    src: unrar_completed.sh.j2
    dest: '{{ config_directory }}/{{ item }}/unrar_completed.sh'
    owner: servarr
    group: servarr
    mode: '550'
  loop: 
    - 'transmission-films'
    - 'transmission-tv'