---
- name: Start traefik container
  tags:
    - traefik
    - container
  docker_container:
    name: traefik
    image: "traefik:{{ docker_image_version }}"
    state: "{{ docker_state }}"
    restart: "{{ docker_restart }}"
    restart_policy: "{{ docker_restart_policy }}"
    recreate: "{{ docker_recreate }}"
    volumes:
      - "{{ traefik_config_directory }}:/etc/traefik:ro"
    networks:
      - name: "{{ traefik_macvlan_network }}"
        ipv4_address: "{{ traefik_ip }}"
      - name: "{{ docker_network }}"
    dns_servers:
      - "{{ dns_primary }}"
      - "{{ dns_secondary }}"
    env:
      TZ: "{{ timezone }}"
    labels:
      traefik.enable: "false"
      homepage.group: "Infrastructure"
      homepage.name: "Traefik"
      homepage.icon: "traefik.png"
      homepage.description: "Reverse Proxy"
      homepage.href: "http://{{ traefik_ip }}:8080"
