---
- name: Ensure config directory is present
  tags:
    - traefik
    - config
  file:
    path: "{{ config_directory }}/traefik"
    state: directory
    owner: servarr
    group: servarr
    mode: "{{ directory_mode }}"

- name: Template config files
  tags:
    - traefik
    - config
  template:
    src: "{{ item }}.j2"
    dest: "{{ config_directory }}/traefik/{{ item }}"
    owner: servarr
    group: servarr
    mode: "600"
  loop:
    - "traefik.toml"
