# Plex Media Server
# https://docs.linuxserver.io/images/docker-plex
---
- name: Start container
  tags:
    - container
    - plex
  docker_container:
    name: plex
    image: lscr.io/linuxserver/plex:latest
    state: "{{ docker_state }}"
    restart: "{{ docker_restart }}"
    restart_policy: "{{ docker_restart_policy }}"
    recreate: "{{ docker_recreate }}"
    network_mode: host
    volumes:
      - "{{ config_directory }}/plex:/config"
      - "{{ data_directory }}/media:/media"
    dns_servers:
      - "{{ dns_primary }}"
      - "{{ dns_secondary }}"
    env:
      PUID: "{{ servarr_uid }}"
      PGID: "{{ servarr_gid }}"
      VERSION: "docker"
      PLEX_CLAIM: "{{ plex_claim }}"
