# https://github.com/pi-hole/docker-pi-hole#installing-on-ubuntu
---
- name: Disable DNS stub resolver
  lineinfile:
    dest: /etc/systemd/resolved.conf
    state: present
    regexp: "^#?DNSStubListener=yes$"
    line: "DNSStubListener=no"
  register: dns_stub_resolver

- name: Symlink DNS resolver settings
  file:
    dest: /etc/resolv.conf
    src: /run/systemd/resolve/resolv.conf
    owner: root
    group: root
    state: link
  when: dns_stub_resolver is changed

- name: Restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
  when: dns_stub_resolver is changed

- name: Start container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    state: stopped
    # state: "{{ docker_state }}"
    restart: "{{ docker_restart }}"
    restart_policy: "{{ docker_restart_policy }}"
    recreate: "{{ docker_recreate }}"
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    capabilities:
      - NET_ADMIN
    dns_servers:
      - "{{ dns_primary }}"
      - "{{ dns_secondary }}"
    env:
      TZ: "{{ timezone }}"
      WEBPASSWORD: "{{ pihole_password }}"
    labels:
      traefik.enable: "false"

- name: UFW - Allow TCP ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "53"
    - "80"
    - "443"

- name: UFW - Allow UDP ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop:
    - "53"
    - "67"
