# https://github.com/crocodilestick/Calibre-Web-Automated
---
- name: Start container
  tags:
    - calibre-web-automated
    - container
  docker_container:
    name: calibre-web-automated
    image: crocodilestick/calibre-web-automated:latest
    state: "{{ docker_state }}"
    restart: "{{ docker_restart }}"
    restart_policy: "{{ docker_restart_policy }}"
    recreate: "{{ docker_recreate }}"
    volumes:
      - "{{ config_directory }}/calibre-web-automated:/config"
      - "{{ data_directory }}/books/ingest:/cwa-book-ingest"
      - "{{ data_directory }}/books/library:/calibre-library"
    networks:
      - name: "{{ docker_network }}"
    dns_servers:
      - "{{ dns_primary }}"
      - "{{ dns_secondary }}"
    ports:
      - "{{ host_port }}:8083"
    env:
      PUID: "{{ servarr_uid }}"
      PGID: "{{ servarr_gid }}"
      TZ: "{{ timezone }}"
      NETWORK_SHARE_MODE: "true"
    labels:
      traefik.enable: "false"
      homepage.group: "Media"
      homepage.name: "Calibre"
      homepage.icon: "calibre-web.png"
      homepage.description: "eBook library"
      homepage.href: "http://{{ network_localhost }}:{{ host_port }}"
